#!/bin/sh

export D2R_HOME="${D2R_HOME:-$PWD}"

if [ ! -e "$D2R_HOME" ]
then
    echo "$D2R_HOME does not exist" 1>&2
    exit 1
fi

JAR="$D2R_HOME/adaptationDesignToRuntime.jar"
CLASS="it.polimi.modaclouds.adaptationDesignTime4Cloud.Main"
if [ ! -e "$JAR" ]
then
    echo "Can't find jarfile to run"
    exit 1
fi

# Deal with Cygwin path issues
cygwin=false
case "`uname`" in
    CYGWIN*) cygwin=true;;
esac
if [ "$cygwin" = "true" ]
then
    JAR=`cygpath -w "$JAR"`
    D2R_HOME=`cygpath -w "$D2R_HOME"`
fi

JVM_ARGS=${JVM_ARGS:--Xmx1200M}

#exec java  $JVM_ARGS -jar "$JAR" "$@"
exec java $JVM_ARGS -cp "$JAR:lib/*" $CLASS "$@"